[versions]
lombok = "1.18.30"
annotations = "24.1.0"
caffeine = "3.1.8"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
caffeine = { module = "com.github.ben-manes.caffeine:guava", version.ref = "caffeine" }
