[versions]
lombok = "1.18.26"
annotations = "24.0.0"
caffeine = "3.1.4"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
caffeine = { module = "com.github.ben-manes.caffeine:guava", version.ref = "caffeine" }
